apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - name: github
      mappingMethod: claim
      type: GitHub
      github:
        clientID: Ov23liucCykskLCqr0rY
        clientSecret:
          name: github-oauth-secret
        organizations:
          - ExternalOpenShiftAuthz

    - name: local-htpasswd
      mappingMethod: claim
      type: HTPasswd
      htpasswd:
        fileData:
          name: htpass-secret

