apiVersion: v1
data:
  htpasswd: dXNlcjE6JDJ5JDA1JHlCOE5CVXVFLkViSFB2YXRYSms0S2VJY3gyb3haeGRDbi94clBxZ1lqT2RnTnI5b25GaFRXCnVzZXIyOiQyeSQwNSRaZC8uN3ZPZC84U0VGWTZzRDIuRkp1VHdOblBja3o3MElYT0dnc0xoR0w0OThiWWdTdmNvMgphY21lLXVzZXIxOiQyeSQwNSRXa21idVhNNWtXR2hnbGVVaDdOV0plV1NFSHNHT1pWRHl4Y0xyMzJKQVh5SjhMUW0xTVdXQwo=
kind: Secret
metadata:
  creationTimestamp: null
  name: htpass-secret
  namespace: openshift-config
