apiVersion: user.openshift.io/v1
kind: User
metadata:
  name: user1
groups: null
identities:
- local-htpasswd:user1

--- 

apiVersion: user.openshift.io/v1
kind: User
metadata:
  name: user2
groups: null
identities:
- local-htpasswd:user2

---

apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: tier-free-users
users: []

---

apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: tier-premium-users
users: []

---

apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: tier-enterprise-users
users: []

