# ###############################
# Define the htpasswd-based users
# ###############################

apiVersion: user.openshift.io/v1
kind: User
metadata:
  name: acme-user1
groups: null
identities:
- local-htpasswd:acme-user1

---

apiVersion: user.openshift.io/v1
kind: User
metadata:
  name: acme-user2
groups: null
identities:
- local-htpasswd:acme-user2

---

# #############################################
# Establish the group membership for all users.
# #############################################

# Define group for MaaS users which is used with the CLusterRoleBindings to give the correct cluster permissions
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: maas-users
users: [bryonbaker, noyitz, bartoszmajsak, butler54, nagarajan-ethan, acme-user1, acme-user2]

---

# This group is used to give users access to the "serverless" models.
# NOTE: The membership is the same as for "maas-users" so this group could probably be replace by 
# the "maas-users" group
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: serverless-users
users: [bryonbaker, noyitz, bartoszmajsak, butler54, nagarajan-ethan, acme-user1, acme-user2]

---

# Users from the Red Hat company
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: redhat-users
users: [bryonbaker, noyitz, bartoszmajsak, butler54]

---

# Users from Acme Inc company
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: acme-inc-users
users: [acme-user1, acme-user2]

---

# Define group for Ethan Group company
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: ethan-group-users
users: [nagarajan-ethan]

---

# #############################################################################################
# Define the Cluster Role Bindings for the groups so they access the cluster to get the api key
# #############################################################################################

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: group-view-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: maas-users

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-config-viewer
rules:
- apiGroups: ["config.openshift.io"]
  resources: ["ingresses"]
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: group-ingress-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-config-viewer
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: maas-users
