kind: DataScienceCluster
apiVersion: datasciencecluster.opendatahub.io/v2
metadata:
 name: default-dsc
 labels:
   app.kubernetes.io/name: datasciencecluster
spec:
 components:
   dashboard:
     managementState: Managed
   aipipelines:
     managementState: Managed
   feastoperator:
     managementState: Removed
   kserve:
     managementState: Managed
   llamastackoperator:
     managementState: Removed
   kueue:
     defaultClusterQueueName: default
     defaultLocalQueueName: default
     managementState: Unmanaged
   modelregistry:
     managementState: Managed
     registriesNamespace: rhoai-model-registries
   ray:
     managementState: Removed
   workbenches:
     managementState: Managed
   trainingoperator:
     managementState: Removed
   trustyai:
     managementState: Removed
