# RBAC for maas-api namespace - allows app to access ConfigMaps in maas-api
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: maas-toolbox-role
  namespace: maas-api
  labels:
    app: maas-toolbox
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: maas-toolbox-rolebinding
  namespace: maas-api
  labels:
    app: maas-toolbox
subjects:
- kind: ServiceAccount
  name: maas-toolbox-sa
  namespace: maas-toolbox
roleRef:
  kind: Role
  name: maas-toolbox-role
  apiGroup: rbac.authorization.k8s.io
---
# ClusterRole for reading OpenShift Groups (cluster-scoped resource)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: maas-toolbox-group-reader
  labels:
    app: maas-toolbox
rules:
- apiGroups: ["user.openshift.io"]
  resources: ["groups"]
  verbs: ["get", "list"]
---
# ClusterRoleBinding to grant Group read access to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: maas-toolbox-group-reader-binding
  labels:
    app: maas-toolbox
subjects:
- kind: ServiceAccount
  name: maas-toolbox-sa
  namespace: maas-toolbox
roleRef:
  kind: ClusterRole
  name: maas-toolbox-group-reader
  apiGroup: rbac.authorization.k8s.io
---
# ClusterRole for managing LLMInferenceService resources (namespaced, but need cluster-wide access)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: maas-toolbox-llminferenceservice-manager
  labels:
    app: maas-toolbox
rules:
- apiGroups: ["serving.kserve.io"]
  resources: ["llminferenceservices"]
  verbs: ["get", "list", "update", "patch"]
---
# ClusterRoleBinding to grant LLMInferenceService management access to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: maas-toolbox-llminferenceservice-manager-binding
  labels:
    app: maas-toolbox
subjects:
- kind: ServiceAccount
  name: maas-toolbox-sa
  namespace: maas-toolbox
roleRef:
  kind: ClusterRole
  name: maas-toolbox-llminferenceservice-manager
  apiGroup: rbac.authorization.k8s.io
---
# ClusterRole for reading Namespaces (cluster-scoped resource)
# Required for namespace existence validation
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: maas-toolbox-namespace-reader
  labels:
    app: maas-toolbox
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
---
# ClusterRoleBinding to grant Namespace read access to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: maas-toolbox-namespace-reader-binding
  labels:
    app: maas-toolbox
subjects:
- kind: ServiceAccount
  name: maas-toolbox-sa
  namespace: maas-toolbox
roleRef:
  kind: ClusterRole
  name: maas-toolbox-namespace-reader
  apiGroup: rbac.authorization.k8s.io

