apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: apps
  annotations:
    # Ensure this deploys after any future "cluster-basics" bundles if you add them.
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: default
  source:
    repoURL: 'https://github.com/bryonbaker/maas-experiments'
    targetRevision: main
    path: components/apps/keycloak/base
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    # Manual sync - changes require manual sync from Argo CD UI/CLI
    syncOptions:
      - CreateNamespace=true
      # Optional but useful in day-2:
      - ApplyOutOfSyncOnly=true
  preserveResourcesOnDeletion: false
  revisionHistoryLimit: 5